# Generated by Django 2.2.6 on 2022-02-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220129_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст поста сюда.', verbose_name='Текст поста'),
        ),
    ]
